#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Stop the service if it's running. Don't disable on upgrade.
        if systemctl is-active --quiet nattunnel.service; then
            systemctl stop nattunnel.service || true
        fi
        if [ "$1" = "remove" ]; then
            systemctl disable nattunnel.service >/dev/null 2>&1 || true
        fi
        ;;
esac

exit 0
